


const LEVELS = [
  {
    id: 1,
    name: "🌱 Beginner Meadow",
    tables: [1],
    story: "Welcome adventurer! Let's begin your journey.",
	quizType: "multiple-choice",
	questionOrder: "sequential",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: null
  },
  {
    id: 2,
    name: "🌲 Forest of Twos",
    tables: [10],
    story: "The forest rabbits need your help.",
	quizType: "numeric-keypad",
	questionOrder: "random",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: null
  },
  {
    id: 3,
    name: "🌊 River Crossing",
    tables: [2],
    story: "Answer correctly to cross the river.",
	quizType: "multiple-choice",
	questionOrder: "sequential",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: null
  },
  {
    id: 4,
    name: "⛰️ Mountain Pass",
    tables: [3],
    story: "The mountain troll is waiting.",
	quizType: "multiple-choice",
	questionOrder: "sequential",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: null
  },
  {
    id: 5,
    name: "🦅 Eagle Heights",
    tables: [2,3,4],
    story: "Fly high with the eagles.",
	quizType: "multiple-choice",
	questionOrder: "random",
	questionCount: 20,
	passingScore: 16,
	maxSeconds: null
  },
  {
    id: 6,
    name: "🏜️ Desert Trail",
    tables: [2,3,4],
    story: "Can you survive the desert?",
	quizType: "numeric-keypad",
	questionOrder: "random",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: 180
  },
  {
    id: 7,
    name: "❄️ Ice Cave",
    tables: [5],
    story: "The cave is very cold!",
	quizType: "multiple-choice",
	questionOrder: "sequential",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: null
  },
  {
    id: 8,
    name: "🌋 Volcano Path",
    tables: [4,5],
    story: "Watch out for lava.",
	quizType: "multiple-choice",
	questionOrder: "random",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: 100
  },
  {
    id: 9,
    name: "🐉 Dragon Valley",
    tables: [6],
    story: "The dragon guards the valley.",
	quizType: "multiple-choice",
	questionOrder: "sequential",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: null
  },
  {
    id: 10,
    name: "🏰 Castle of Tens",
    tables: [4,5,6],
    story: "The final challenge awaits.",
	quizType: "multiple-choice",
	questionOrder: "random",
	questionCount: 20,
	passingScore: 16,
	maxSeconds: null
  },
  {
    id: 11,
    name: "🏰 Castle of Tens",
    tables: [4,5,6],
    story: "The final challenge awaits.",
	quizType: "numeric-keypad",
	questionOrder: "random",
	questionCount: 20,
	passingScore: 16,
	maxSeconds: 120
  },
  {
    id: 12,
    name: "🏰 Castle of Tens",
    tables: [7],
    story: "The dragon guards the valley.",
	quizType: "multiple-choice",
	questionOrder: "sequential",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: null
  },
  {
    id: 13,
    name: "🏰 Castle of Tens",
    tables: [7],
    story: "The dragon guards the valley.",
	quizType: "multiple-choice",
	questionOrder: "random",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: null
  },
  {
    id: 14,
    name: "🏰 Castle of Tens",
    tables: [6,7],
    story: "The dragon guards the valley.",
	quizType: "multiple-choice",
	questionOrder: "random",
	questionCount: 20,
	passingScore: 16,
	maxSeconds: null
  },
  {
    id: 15,
    name: "🏰 Castle of Tens",
    tables: [8],
    story: "The dragon guards the valley.",
	quizType: "multiple-choice",
	questionOrder: "sequential",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: null
  },
  {
    id: 16,
    name: "🏰 Castle of Tens",
    tables: [8],
    story: "The dragon guards the valley.",
	quizType: "multiple-choice",
	questionOrder: "random",
	questionCount: 10,
	passingScore: 8,
	maxSeconds: null
  },
  {
    id: 17,
    name: "🏰 Castle of Tens",
    tables: [7,8],
    story: "The dragon guards the valley.",
	quizType: "multiple-choice",
	questionOrder: "random",
	questionCount: 20,
	passingScore: 16,
	maxSeconds: null
  },
  {
    id: 18,
    name: "🏰 Castle of Tens",
    tables: [6,7,8],
    story: "The final challenge awaits.",
	quizType: "numeric-keypad",
	questionOrder: "random",
	questionCount: 20,
	passingScore: 16,
	maxSeconds: 100
  }
];

const GOOD_MESSAGES = [
  "🎉 Amazing!",
  "⭐ Great job!",
  "🚀 Fantastic!",
  "🦄 Wonderful!",
  "🥳 Excellent!",
  "🎉 Amazing!",
  "⭐ Great job!",
  "🚀 Fantastic!",
  "🦄 Wonderful!",
  "🥳 Excellent!",
  "🎉 Amazing!",
  "⭐ Great job!",
  "🚀 Fantastic!",
  "🦄 Wonderful!",
  "🥳 Excellent!",
  "🎉 Amazing!",
  "⭐ Great job!",
  "🚀 Fantastic!",
  "🦄 Wonderful!",
  "🥳 Excellent!",
  "🎉 Amazing!",
  "⭐ Great job!",
  "🚀 Fantastic!",
  "🦄 Wonderful!",
  "🥳 Excellent!",
  "🎉 Amazing!",
  "⭐ Great job!",
  "🚀 Fantastic!",
  "🦄 Wonderful!",
  "🥳 Excellent!",
  "🎉 Amazing!",
  "⭐ Great job!",
  "🚀 Fantastic!",
  "🦄 Wonderful!",
  "🥳 Excellent!",
  "🎉 Amazing!",
  "⭐ Great job!",
  "🚀 Fantastic!",
  "🦄 Wonderful!",
  "🥳 Excellent!",
  "🎉 Amazing!",
  "⭐ Great job!",
  "🚀 Fantastic!",
  "🦄 Wonderful!",
  "🥳 Excellent!"
];


const TRY_AGAIN_MESSAGES = [
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!",
  "💪 Keep going!",
  "😊 Nice try!",
  "🌟 You can do it!",
  "❤️ Almost there!"
];

